export * from "@/widgets/chess/piece"
export * from "@/widgets/chess/cell"
export * from "@/widgets/chess/pieceType"
export * from "@/widgets/chess/board"
export * from "@/widgets/chess/matchInfo"   
export * from "@/widgets/chess/timer"
export * from "@/widgets/chess/coronation"
export * from "@/widgets/chess/pieceImages"